//! Operational validation of the event → trigger → job pipeline
//! (Milestone 9, Epic 2, Task 2.3).
//!
//! These tests exercise the listener subsystem end-to-end:
//!
//! * a matching event creates exactly one trigger per matching listener,
//! * a non-matching event creates no triggers,
//! * multiple matching listeners fan out (one trigger each),
//! * per-listener rate limiting caps trigger creation within a window, and
//! * a created trigger is converted into a job and executed through the same
//!   `Orchestrator` dispatch path validated in Epic 1 (observed via a
//!   `TaskService` test double).
//!
//! The pipeline itself already exists (`ListenerOrchestrator::process_event`
//! creates triggers; `Orchestrator::execute_trigger` converts a trigger into a
//! job and runs it via `execute_job`), so no production glue is added here —
//! the tests validate the existing wiring.

use async_trait::async_trait;
use paladin::application::services::orchestration::Orchestrator;
use paladin::application::services::orchestration::listener::{
    EventListener, ListenerConfig, ListenerOrchestrator,
};
use paladin::application::services::orchestration::types::ListenerError;
use paladin::core::base::component::action::Action;
use paladin::core::base::component::event::Event;
use paladin::core::platform::container::task::{TaskError, TaskService};
use paladin::core::platform::container::trigger::{Trigger, TriggerCondition};
use std::sync::{Arc, Mutex};

/// A listener that matches events whose `event_type` starts with `prefix` and
/// emits a trigger targeting `target_service`.
struct PrefixListener {
    name: String,
    prefix: String,
    target_service: String,
    config: ListenerConfig,
    conditions: Vec<TriggerCondition>,
}

impl PrefixListener {
    fn new(name: &str, prefix: &str, target_service: &str, config: ListenerConfig) -> Self {
        Self {
            name: name.to_string(),
            prefix: prefix.to_string(),
            target_service: target_service.to_string(),
            config,
            conditions: Vec::new(),
        }
    }
}

#[async_trait]
impl EventListener for PrefixListener {
    fn name(&self) -> &str {
        &self.name
    }

    fn description(&self) -> &str {
        "Prefix-matching listener for pipeline validation"
    }

    fn conditions(&self) -> &[TriggerCondition] {
        &self.conditions
    }

    async fn should_process(&self, event: &Event) -> bool {
        event.event_type.starts_with(&self.prefix)
    }

    async fn create_trigger(&self, event: Event) -> Result<Trigger, ListenerError> {
        let action = Action::new(
            "Pipeline Action".to_string(),
            "Generated by prefix listener".to_string(),
            self.name.clone(),
            self.target_service.clone(),
        );

        let condition = TriggerCondition {
            event_type_pattern: format!("{}*", self.prefix),
            source_pattern: None,
            payload_conditions: vec![],
            min_priority: None,
            time_conditions: None,
        };

        Ok(Trigger::new(
            format!("Trigger for {}", event.event_type),
            "Generated trigger".to_string(),
            self.name.clone(),
            self.target_service.clone(),
            event,
            action,
            condition,
        ))
    }

    fn config(&self) -> &ListenerConfig {
        &self.config
    }

    fn update_config(&mut self, config: ListenerConfig) {
        self.config = config;
    }

    async fn health_check(&self) -> Result<bool, ListenerError> {
        Ok(true)
    }
}

/// A `TaskService` that records each invocation into a shared, synchronized log,
/// giving the test an observable record that the trigger reached job execution.
#[derive(Debug, Clone)]
struct RecordingService {
    service_name: String,
    log: Arc<Mutex<Vec<String>>>,
}

impl RecordingService {
    fn new(service_name: &str, log: Arc<Mutex<Vec<String>>>) -> Self {
        Self {
            service_name: service_name.to_string(),
            log,
        }
    }
}

#[async_trait]
impl TaskService for RecordingService {
    fn name(&self) -> &str {
        &self.service_name
    }

    async fn execute(&self, _action: &Action) -> Result<Option<serde_json::Value>, TaskError> {
        self.log.lock().unwrap().push(self.service_name.clone());
        Ok(Some(serde_json::json!({ "service": self.service_name })))
    }

    fn clone_service(&self) -> Box<dyn TaskService> {
        Box::new(self.clone())
    }
}

fn event(event_type: &str) -> Event {
    Event::new(
        event_type.to_string(),
        serde_json::json!({ "data": "test" }),
        "pipeline-test-source".to_string(),
    )
}

#[tokio::test]
async fn matching_event_creates_exactly_one_trigger() {
    let listener = ListenerOrchestrator::new();
    listener
        .register_listener(Box::new(PrefixListener::new(
            "alpha",
            "order_",
            "order_service",
            ListenerConfig::default(),
        )))
        .await
        .expect("register listener");

    let triggers = listener
        .process_event(event("order_created"))
        .await
        .expect("process event");

    assert_eq!(triggers.len(), 1, "matching event must create one trigger");
    assert!(
        listener.get_next_trigger().await.is_some(),
        "trigger must be queued for processing"
    );
}

#[tokio::test]
async fn non_matching_event_creates_no_trigger() {
    let listener = ListenerOrchestrator::new();
    listener
        .register_listener(Box::new(PrefixListener::new(
            "alpha",
            "order_",
            "order_service",
            ListenerConfig::default(),
        )))
        .await
        .expect("register listener");

    let triggers = listener
        .process_event(event("payment_settled"))
        .await
        .expect("process event");

    assert!(
        triggers.is_empty(),
        "non-matching event must not create a trigger"
    );
    assert!(
        listener.get_next_trigger().await.is_none(),
        "no trigger should be queued"
    );
}

#[tokio::test]
async fn multiple_matching_listeners_fan_out_one_trigger_each() {
    let listener = ListenerOrchestrator::new();
    listener
        .register_listener(Box::new(PrefixListener::new(
            "alpha",
            "order_",
            "service_a",
            ListenerConfig::default(),
        )))
        .await
        .expect("register alpha");
    listener
        .register_listener(Box::new(PrefixListener::new(
            "beta",
            "order_",
            "service_b",
            ListenerConfig::default(),
        )))
        .await
        .expect("register beta");

    let triggers = listener
        .process_event(event("order_created"))
        .await
        .expect("process event");

    assert_eq!(
        triggers.len(),
        2,
        "each matching listener must create exactly one trigger"
    );
}

#[tokio::test]
async fn rate_limit_caps_trigger_creation_within_window() {
    // A listener limited to a single trigger per (long) window.
    let config = ListenerConfig {
        max_triggers_per_window: 1,
        time_window_seconds: 3600,
        ..ListenerConfig::default()
    };

    let listener = ListenerOrchestrator::new();
    listener
        .register_listener(Box::new(PrefixListener::new(
            "alpha",
            "order_",
            "order_service",
            config,
        )))
        .await
        .expect("register listener");

    let mut total_triggers = 0;
    for _ in 0..3 {
        let triggers = listener
            .process_event(event("order_created"))
            .await
            .expect("process event");
        total_triggers += triggers.len();
    }

    assert_eq!(
        total_triggers, 1,
        "rate limit must cap trigger creation at the window maximum"
    );

    let stats = listener
        .get_listener_stats("alpha")
        .await
        .expect("listener stats");
    assert_eq!(stats.events_processed, 3, "all events are processed");
    assert_eq!(stats.triggers_created, 1, "only one trigger is created");
}

#[tokio::test]
async fn trigger_is_converted_to_job_and_executed() {
    let log = Arc::new(Mutex::new(Vec::new()));

    let orchestrator = Orchestrator::new();

    // The trigger targets "order_service"; register a matching task service so
    // the generated job has an executor.
    orchestrator
        .register_task_service(Box::new(RecordingService::new(
            "order_service",
            log.clone(),
        )))
        .await
        .expect("register task service");

    orchestrator
        .register_event_listener(Box::new(PrefixListener::new(
            "alpha",
            "order_",
            "order_service",
            ListenerConfig::default(),
        )))
        .await
        .expect("register listener");

    orchestrator.start().await.expect("orchestrator start");

    let trigger_ids = orchestrator
        .process_event(event("order_created"))
        .await
        .expect("process event");

    assert_eq!(trigger_ids.len(), 1, "one trigger should be created");

    let executed = log.lock().unwrap().clone();
    assert_eq!(
        executed,
        vec!["order_service".to_string()],
        "the trigger must be dispatched to its target service as a job"
    );
}
