pub mod arsenal;
pub mod arsenal_config_test;
pub mod arsenal_domain_test;
pub mod arsenal_port_test;
pub mod battalion;
pub mod circuit_breaker_test;
pub mod cli_agent_commands_test;
pub mod cli_arsenal_commands_test;
pub mod cli_battalion_commands_test;
pub mod embedding_port_tests;
pub mod handoff_service_test;
pub mod maneuver_domain_tests;
pub mod mcp_protocol_test;
pub mod mock_llm_adapter_test;
pub mod paladin_builder_arsenal_test;
pub mod paladin_builder_test;
pub mod paladin_config_test;
pub mod paladin_entity_test;
pub mod paladin_error_test;
pub mod paladin_execution_service_test;
pub mod parser_tests;
// TODO: Re-enable after fixing LlmPort trait changes
// pub mod prompt_generation_service_test;
pub mod sanctum_domain_tests;
pub mod sanctum_port_tests;
